version: '3'

services:

  crm-app:
    image: djangocrm:1
    container_name: crm-app
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432

      - SECRET_KEY=kfd83a9$$mw#cj9@v9)ym!--1ksxz$$=+e$$+jlnj^ou10whke!l^
      - ENV_TYPE=dev
    depends_on:
      - crm-db
      - nginx
    ports:
      - 8000:8000
    networks:
      main:
          aliases:
              - crm-app
  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql/:/var/run/postgresql
    networks:
      main:
          aliases:
              - crm-db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    links:
      - crm-app:crm-app
    depends_on:
      - crm-app:
          condition: service_healthy
    networks:
      main:
          aliases:
              - nginx

volumes:
  postgres_data:
  static_volume:
  
networks:
  nw: 
  main:
